#version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGODB_DB=user_management
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: